spring:
   datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:~/Spring/msa/gateway/h2/user
      username: sa
      password: '{cipher}AYDLyob21OMK7ZFTnUSFyyQQPelpNjzLdy59Wnr6JlzdoBO/RChGYhm5l5QzyuTV6EGlTheJjU04PzPpaobMB3lXc/az3kcL1+BeYg+fqo65EH3AV3wUk8GzpotEbmnio9nE7rYrEmBGIYjGZItRlvI9+gxOp61D+/JOw/7f0jpUh4emBKZ28bWVgTmH+PnSaRADzw/heQujP9+YcNJV9HTXLiVJXDCi3op6Fm0ZJZZxMDRHq+e8HeYzmv4Rx9Z+23urWqVm7v2POo1HCWeLMKP9b2xFVYzRi9qrFlEgCmF0Jn89Xn73d4UHuQAiVKDaVYjkH7ILYraHPnDQVYfeRWHwmJ8F5aAW52qUo23iQjMj9yiOe1LOiXj1UWufjoxymJIGodWTbJzlebkKh0nmM23/dfhnrAnG0goRXeGaianMFX7NaV2nj/QLCPydVGMUAQxynK1Kk4R15YDxpkdAxK6Fw+qeN7uJxi5WT6TUiAA7V0WWuhelGXXylC1f4pAaqSY1pmOKRtbxcrlaSEBL8ZZfeE5gX1uBjKMS06S+9pgbiw=='
   jpa:
      hibernate:
         ddl-auto: update
         show-sql: true
